# Spring配置
spring:
  datasource:
    url: jdbc:mysql://119.3.91.32:3306/demo_ds_0?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: xieyang123
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: xieyang123
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: datasource,common
  # 文件上传
  servlet:
    multipart:
      max-file-size:  500MB
      max-request-size:  500MB
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
    converters:
      preferred-json-mapper: gson
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 47.105.125.178
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 111111
  # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      # 未使用到ES 关闭存储
      repositories:
        enabled: false

# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    uri-encoding: UTF-8


# 项目相关配置
common:
  # 名称
  name: tatu
  # 版本
  version: 3.0.0
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径
  profileM: /Users/cullen/Downloads/
  # 文件上传路径
  profileL: /root/downloads/
  # 获取ip地址开关
  addressEnabled: true

tatu:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  mob:
    appKey: 你的appKey
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false



# 日志配置
logging:
  level:
    root: info
    org.springframework.web: trace
    com.cullen.ssq: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cullen.tatu.server.*.mapper
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*/*Mapper.xml
  # 加载全局的配置文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

  # 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger界面内容配置
swagger:
  title: tatu API接口文档
  description: tatu Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://dengtatu.cn/cullen
  contact:
    name: Cullen
    url: http://dengtatu.cn/cullen
    email: newxieyang@msn.cn

# 忽略鉴权url
ignored:
  urls:
    - /account/register
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /download/**
    - index
    - /tatu/actuator/**
    - /api/dictData/getByType/**
    - /api/common/**
    - /static/**